### PR TITLE
Add orderless-kwd.el

### PR DESCRIPTION
**Pull request by minad**
As discussed via mail and in the issues #30 and #162.

### CODE REVIEW

**Comment by oantolin** [comment]
You have several occurrences of `(or (window-buffer (minibuffer-selected-window)))`. Are they missing a `(current-buffer)` branch of the `or`?

**Comment by oantolin** [comment]
I was about to suggest the orig-buffer helper. :) I've added you as a collaborator to the repo, too, you should have received an invitation.

**Comment by oantolin** [comment]
Well, this looks great to me! I think on my list of suggestions the only thing left is maybe shortening some of the keywords. Feel free to do that or not as you prefer, and to merge when you are done (I have to go do some stuff and probably won't be back for several hours).

**Comment by minad** [comment]
> Well, this looks great to me! I think on my list of suggestions the only thing left is maybe shortening some of the keywords. Feel free to do that or not as you prefer, and to merge when you are done (I have to go do some stuff and probably won't be back for several hours).

Thanks. I'd like shorter names, but I am a little torn on the shortening. I don't really like `maj` or `chg` (which bites the `buffer-modified-p` convention). As I wrote in my mail, I could also lookup the first or unique prefix. Alternatively I could match the keyword with `orderless-flex` and take the first matching one. That's maybe the nerdiest solution, since it reuses the internal Orderless flex facility. ;)

**Comment by oantolin** [comment]
Another option: just don't shorten `mode` but keep the other shortenings I suggested.

**Comment by minad** [comment]
Okay, I tried the flex idea. It is ridiculously bad, since it matches too often. I cannot understand why anyone likes the flex style. I may like an *anchored* flex style, but not the one which just matches inside a word.

**Comment by oantolin** [comment]
> Okay, I tried the flex idea. It is ridiculously bad, since it matches too often. I cannot understand why anyone likes the flex style. I may like an _anchored_ flex style, but not the one which just matches inside a word.

I've never liked flex either! Maybe anchored flex is usable, I've never tried that.

**Comment by oantolin** [comment]
Thanks for contributing this and for handling the merging too!

**Comment by minad** [comment]
You're welcome. For now I've went with the simplest solution of short three-letter keywords, similar to what you had suggestd. We can adjust this if it turns out too limited at some point. We'll probably add more matchers too in the future.

**Pull request merged**
