### PR TITLE
Annotation matching

### PR DESCRIPTION
**Pull request by minad**
This is a prototype for https://github.com/oantolin/orderless/issues/88#issuecomment-1944468179. The patch is based on the changes from #161. 

This is a draft for now since #161 should be merged first (and independently of this PR). Also it is not clear if we want this feature in Orderless after all. I think it is nice to have and almost free as soon as we allow the pattern compiler to additionally generate a predicate function. Such a generalization is useful because it enables us to implement #88.

### CODE REVIEW

**Comment by oantolin** [comment]
It's annoying that you have to call the affixation function on each candidate separately, but this is forced by the implementation choice of using the completion predicate for any non-regexp matching. And that is a very sensible choice, so I guess we can live with one-at-a-timing the affixation functions.

I also appreciate you adding an optional argument to `orderless-pattern-compiler` to keep the previous return value as the default, but I am tempted to just change the return value to the new format. 😬

**Comment by minad** [comment]
> It's annoying that you have to call the affixation function on each candidate separately, but this is forced by the implementation choice of using the completion predicate for any non-regexp matching. And that is a very sensible choice, so I guess we can live with one-at-a-timing the affixation functions.

That's why the annotation-function is preferred. But you should not be worried about the additional inefficiency here given that the matcher is already inefficient since it generates all these annotations. Nevertheless this feature has been requested so many times. I like how well it fits into the Orderless framework here. It also kind of boosts the usefulness of Marginalia.

We could also document additional predicate-based matchers in the wiki or maybe implement an extensible query-language like this: @regexp (annotation), @content:regexp (buffer content) @mode:regexp (buffer mode), ... I think such a feature is out of scope of Orderless (as I had also mentioned in #30), also since they are completion category-dependent. But having the ability to fit such functionality into Orderless is still great.

> I also appreciate you adding an optional argument to orderless-pattern-compiler to keep the previous return value as the default, but I am tempted to just change the return value to the new format.

I think it is better to preserve the calling convention we have right now. I like that we can implement this in a backward compatible way.

**Comment by oantolin** [comment]
> We could also document additional predicate-based matchers in the wiki or maybe implement an extensible query-language like this: `@regexp` (annotation), `@content:regexp` (buffer content) `@mode:regexp` (buffer mode), ... I think such a feature is out of scope of Orderless (as I had also mentioned in #30), also since they are completion category-dependent. But having the ability to fit such functionality into Orderless is still great.

Well they are completion category-dependent or not depending on how you define them. If you say `@mode:regexp` matches any string that, as the time of matching, happens to be the name of a buffer whose major-mode matches the regexp, that's not dependent on completion category. And if users decide to only ever using that syntax when they are matching against buffer names, who could blame them?

**Comment by oantolin** [comment]
Oh, there's even a sensible use for `@mode:regexp` when matching non-buffers: of you are matching against files, `@mode:.` matches files that are visited by some buffer!

**Comment by minad** [comment]
Omar Antolín Camarena ***@***.***> writes:

>> We could also document additional predicate-based matchers in the wiki or
> maybe implement an extensible query-language like this: ***@***.***` (annotation),
> ***@***.***:regexp` (buffer content) ***@***.***:regexp` (buffer mode), ... I think
> such a feature is out of scope of Orderless (as I had also mentioned in #30),
> also since they are completion category-dependent. But having the ability to fit
> such functionality into Orderless is still great.
>
> Well they are completion category-dependent or not depending on how you define
> them. If you say ***@***.***:regexp` matches any string that, as the time of
> matching, happens to be the name of a buffer whose major-mode matches the
> regexp, that's not dependent on completion category. And if users decide to only
> ever using that syntax when they are matching against buffer names, who could
> blame them?

You are right about that. What I mean is that for ***@***.***:regexp` we have
to take the candidate string, convert it to a buffer, access the
buffer-local variable major-mode and then match against that value. If
one would use such a predicate against arbitrary other candidates,
already the buffer lookup would fail and return nil. Another example:

(defun orderless-buffer-content (component)
  (unless (equal component "")
    (lambda (str)
      (when-let ((buf (get-buffer str)))
        (with-current-buffer buf
          (save-excursion
            (goto-char (point-min))
            (search-forward-regexp component)))))))

Anyway, the nice thing here is that the annotation matcher is generic
and that the addition opens the door for further experimentation and
advanced functionality.

**Comment by oantolin** [comment]
I think I took your phrase "completion category-dependent" to mean "would look at the completion category" (so I argued they can usefully be defined to not look at the completion category), while you actually just meant "are much more useful for some completion categories than others, which I fully agree with. Sorry for the noise.

**Comment by minad** [comment]
One thing I am not entirely sure about is how these predicates and regexps are combined, in particular if one of the functions returns nil. Can you please check orderless-pattern-compiler carefully?

**Comment by minad** [comment]
> I think I took your phrase "completion category-dependent" to mean "would look at the completion category" (so I argued they can usefully be defined to not look at the completion category), while you actually just meant "are much more useful for some completion categories than others, which I fully agree with. Sorry for the noise.

Looking at the category would be necessary if filters with the same syntax are reused. For example `*regexp` could mean that regexp must match against the content of a buffer or also at the content of file. It could also mean something else for other types. We cannot try all these  different matching methods in order, since that would be unnecessarily expensive. At this point one should rather look at the category or construct different completion styles via orderless-define-completion-style and then register them in completion-category-overrides.

**Comment by oantolin** [comment]
> One thing I am not entirely sure about is how these predicates and regexps are combined, in particular if one of the functions returns nil. Can you please check orderless-pattern-compiler carefully?

Oh, I think there is a problem. All the and-ing seems correct to me, and I think this should work for people who use a single matching style at a time (which I recommend for efficiency reasons anyway). 

Now, if you use multiple matching styles at once for a component, that component is supposed to match if any of the styles match. But what the code does is subtly different: all the regexps are or-ed together, and all of the predicates are or-ed together; so far so good, but the way predicates are used they are implicitly and-ed with the regexps, that is, all regexps need to match and the predicate, if given, must return non-nil too. So you wind up with the equivalent of `(and (or regexps...) (or predicates...))` instead of pure or-ing. Does this make sense?

I don't really see a way around this problem. I'd just document that those are the semantics and call it a day.

**Comment by oantolin** [comment]
Maybe it would be better to just combine all the predicates with `and`. That might be a simpler model to wrap one's head around: for each component at least one of the regexps from the matching styles needs to match, and all of the predicates need to match.

**Comment by minad** [comment]
> Now, if you use multiple matching styles at once for a component, that component is supposed to match if any of the styles match. But what the code does is subtly different: all the regexps are or-ed together, and all of the predicates are or-ed together; so far so good, but the way predicates are used they are implicitly and-ed with the regexps, that is, all regexps need to match and the predicate, if given, must return non-nil too. So you wind up with the equivalent of (and (or regexps...) (or predicates...)) instead of pure or-ing. Does this make sense?

Yes, these subtly weird semantics are exactly why I was asking. As soon as there is a predicate it will be ANDed with the regexps. I also don't see how we could improve this, except by lifting the regexp matching to the predicate level, as soon as other predicate functions are present. But we surely don't want to do this for performance reasons.

Do you think these semantics are too problematic or acceptable for Orderless? The two matchers orderless-without-regexp and orderless-annotation function correctly I think. The problem would be bigger if one starts to add predicated-based matchers to orderless-matching-styles.

**Comment by minad** [comment]
> Maybe it would be better to just combine all the predicates with and. That might be a simpler model to wrap one's head around: for each component at least one of the regexps from the matching styles needs to match, and all of the predicates need to match.

Yes, I had also thought about just dropping orderless--predicate-or and only using orderless--predicate-and everywhere. Do we lose anything if we do that?

**Comment by oantolin** [comment]
I think I'd prefer just and-ing all the predicates. We don't lose any expressive power since people can always `or` their predicates to make a single predicate for orderless, if they need to. I also think the difference between or-ing and and-ing predicates will not come up often at all: I envision predicates mostly used via dispatchers that take a component to one single predicate, as in all of our examples of predicate matching so far.

**Comment by oantolin** [comment]
I went ahead and removed `orderless--predicate-or`.

**Comment by oantolin** [comment]
How would you feel for the annotation matcher to instead of using regexps, calling the whole pattern compiler? That way people can use whatever syntax they use to search candidates to search annotations too.

**Comment by minad** [comment]
> How would you feel for the annotation matcher to instead of using regexps, calling the whole pattern compiler? That way people can use whatever syntax they use to search candidates to search annotations too.

This sounds great! We can probably also do that for orderless-without. I only worry a bit about getting stuck in some recursion.

**Comment by minad** [comment]
Maybe the pattern compiler should be refactored such that we have orderless-pattern-compiler acting on the whole input and orderless--component-compiler acting only on a single component. Then orderless-annotation and orderless -without could use the orderless--component-compiler.

**Comment by minad** [comment]
I've added an orderless--component-compiler which is used by orderless-pattern-compiler and also by orderless-without and orderless-annotation. The component dispatcher uses the orderless-matching-styles but not the dispatching mechanism. Is this limitation acceptable?

**Comment by minad** [comment]
I added a few more small refactorings:

1. orderless-dispatch --> orderless--dispatch (keeping orderless-dispatch as obsolete function)
2. orderless-pattern-compiler -> orderless-compile (keeping obsolete-pattern-compiler as obsolete function, update return value convention of orderless-compile)
3. orderless-affix-dispatch (always ignore single dispatch characters)

**Comment by minad** [comment]
> Well, my idea was that users should be able to use the normal syntax they use to match candidates in order to match annotations, and I think for most users dispatchers are a big part of that syntax.

I am not sure. I find syntax like `@!...` a little bit over the top. But we can do this if you prefer it.

> Maybe the component compiler should take index and total parameters and do dispatch.

Yes, I had considered doing that. I will give it a try.

> The annotation matching functionality could be split into a matching style that returns a predicate that takes a regexp and matches them against the annotation, and a dispatcher that calls the pattern compiler with the appropriate index and total and dispatchers the resulting regexp to there matching style. In this plan the annotation dispatching can not be done through the affix dispatcher, but requires that separate dispatcher. What do you think of this proposal?

No, I don't like this. The advantage of the current approach is that we can register additional syntax via the affix dispatcher, e.g., the `orderless-buffer-content` matcher could be registered for the character `?*`.

**Comment by oantolin** [comment]
> No, I don't like this. The advantage of the current approach is that we can register additional syntax via the affix dispatcher

Sure, but the current affix dispatcher doesn't call the component compiler. And a matching style *cannot* call the dispatching component compiler I'm proposing because matching styles don't have access to the index and total parameters.

One option would be to (1) modify the component compiler as I suggest to do dispatch, but also (2) generalize the affix dispatcher to optionally allow applying some function of the string, index and total to compute a replacement string, and use that to call the component compiler in the annotation case.

**Comment by minad** [comment]
Okay, I've modified orderless--compile-component to also do orderless--dispatch. Could you please take a look? I must admit I don't really understand your proposal regarding index and total. 

I am okay with this approach. The only thing I insist on is that we use the affix dispatcher also for orderless-annotation, since otherwise we would lose the power I've mentioned before with orderless-buffer-content. I would really like to have the ability to register predicate matchers in orderless-affix-dispatch-alist.

**Comment by minad** [comment]
I've read your comment a few times now and I have difficulties understanding it.

> One option would be to (1) modify the component compiler as I suggest to do dispatch, ...

Yes, I've done that.

> ... but also (2) generalize the affix dispatcher to optionally allow applying some function of the string, index and total to compute a replacement string, and use that to call the component compiler in the annotation case.

This part is not clear to me.

**Comment by oantolin** [comment]
I'm probably to sleepy too explain better now. Will write tomorrow. I had not seen you just use 0 and 1 for the index and total; I was thinking of using the actual numbers, which requires some different plumbing to connect the functions.

**Comment by minad** [comment]
> I'm probably to sleepy too explain better now. Will write tomorrow. I had not seen you just use 0 and 1 for the index and total; I was thinking of using the actual numbers, which requires some different plumbing to connect the functions.

Thanks, let's continue the discussion tomorrow.

---

A few more thoughts:

I think I've now understood your proposal of allowing the affix dispatcher to recursively call other dispatchers. Instead of only dispatching to styles one could also dispatch to dispatchers recursively. The annotation dispatcher would dispatch to the annotation string and so on. Not sure if the added complexity is worth it.

It also goes a bit against the idea of this whole PR, since then we could as well not extend Orderless with custom predicate functions but simply stay on the level of regexp matching with additional dispatchers which return some new strings. However we would still miss some power and flexibility, e.g., the orderless-without predicate and allocating a buffer string or a file content string would be too expensive. A custom predicate can match directly against the buffer or the file.

Regarding the 0 and 1, I think that this is okay. As soon as we are on the second level via the orderless-annotation or the orderless-without matcher, we don't have access to the outer positional information anymore, except if we bind it dynamically. One could replace the orderless-annotation matcher with a dispatcher as you suggested, but orderless-without and orderless-buffer-content could not get the same treatment. So for orderless-without and orderless-buffer-content we always lose the position information. As a workaround we could dynamically bind orderless--index and orderless--total and reuse that in the recursive call to orderless--compile-component, but at this point it feels like over-engineering it. I vote then to keep the complexity lower as long as we don't have a real example at hand where we need the actual position information which would justify introducing dynamic variables.

**Comment by minad** [comment]
I created a little bit of chaos here, trying various things, but I think I've arrived at a solution I am happy with. The functions orderless-annotation and orderless-without take two arguments PRED and REGEXP and transform them to a new predicate. The recursive compilation is performed with the actual values of INDEX and TOTAL. The affix dispatcher is unaffected and can stay as is. See b56db3eea43ba67f319defca1ed65666b7f68bd5.

**Comment by minad** [comment]
@oantolin Did you have a chance to take another look at this PR? While the history is a little chaotic, the result in the end looks quite clean to me, so you could also ignore the intermediate comments/commits. ;)

**Comment by oantolin** [comment]
Sorry, I got super busy at work. I'll take a look soon. Thanks for suggesting looking at the end result first.

**Comment by minad** [comment]
> Sorry, I got super busy at work. I'll take a look soon. Thanks for suggesting looking at the end result first.

Oh, sorry for disturbing then and thanks for responding! No worries, there is no urgency here.

**Comment by oantolin** [comment]
You're right that the end result is quite clean! Let me see if I understand correctly: the new component compiler admits a new type of two argument matching style taking a predicate and a regexp, if it runs into ones of those it will call itself recursively and call the matching style on the result? That's pretty neat: the dispatchers always get called with the right index and total now and the affix dispatcher can be used as-is for general negation and for annotations (which now fully use whatever syntax the user has set up). I like it a lot.

**Comment by oantolin** [comment]
(I thought I'd take a brief look to estimate how long it would take me to understand it and actually found it made sense right away —unless my description of it is wrong 🙃)

**Comment by minad** [comment]
> the new component compiler admits a new type of two argument matching style taking a predicate and a regexp, if it runs into ones of those it will call itself recursively and call the matching style on the result? That's pretty neat: the dispatchers always get called with the right index and total now and the affix dispatcher can be used as-is for general negation and for annotations (which now fully use whatever syntax the user has set up).

Yes, this is correct. The user can write things like @!!!foo and compilation is performed with the right index and total. 

The beauty about the approach here is also that the Orderless "formal" language is restricted. Dispatchers, styles and transformers are restricted in what they should do and a clear separation of concerns is enforced between the different functions.

dispatcher : string -> (style or transformer, string)
style : string -> regexp or predicate
transformer : (regexp, predicate) -> predicate

For example, transformers do not have the ability to first modify the input before it is compiled. On the other hand, input modifications (before compilation) are completely the business of the dispatcher.

**Comment by minad** [comment]
> (I thought I'd take a brief look to estimate how long it would take me to understand it and actually found it made sense right away —unless my description of it is wrong 🙃)

Haha, this was my point. No estimation of effort needed. ;)

**Comment by oantolin** [comment]
> I've noticed that Orderless lacks a change log

That's because it used to be finished so no changelog was necessary. 😄

**Comment by minad** [comment]
Omar Antolín Camarena ***@***.***> writes:

>> I've noticed that Orderless lacks a change log
>
> That's because it used to be finished so no changelog was necessary. 😄 

Right. It is finished now. :)

**Comment by minad** [comment]
Omar Antolín Camarena ***@***.***> writes:

> I'm actually tempted to bump the version number all the way to 2.0, when I bump it.

Yeah, why not. We also renamed some APIs and introduced new ones. But
given that Orderless is finally done now, the version 1.0e+INF could be
more appropriate. ;)

**Comment by minad** [comment]
The only argument against bumping to 2.0 directly is that we could have introduced some bugs. So my suggestion would be to bump to 1.1 and a month or so after that bump to 2.0. This way we can catch additional issues. I use this gradual approach for my packages. I could also bump Vertico to 2.0 at this point I think.

**Comment by oantolin** [comment]
Good idea. I'll do 1.1, give some time, eventually remove al obsolete names, and only then tag 2.0

**Comment by ashton314** [comment]
Just wanted to say thank you for implementing this! This is really nice in org-roam for finding notes written on a particular date. I'm sure I'll find other uses for this as time goes on.

**Comment by oantolin** [comment]
And you could also write date matchers that look for notes no later than some date or no earlier than some date, @ashton314. This foundation of @minad's is really very versatile

**Comment by oantolin** [comment]
Gah, first "problem" with the new annotation matcher found! I was having a devil of a time mentioning people on ement.el until I realized the problem was that I was using `completion-at-point` on a string that starts with `@`! 😄 

Of course, this isn't a real problem with the annotation matcher, but I think I should use a different orderless-derived completion style just in ement buffers, or maybe I could globally use a style dispatcher that treats the `@` literally if it is in the first component (the latter is probably not a great idea).

**Comment by minad** [comment]
@oantolin I would just use `=` to override the `@` dispatcher, e.g., `=@oantolin` in Ement.

**Comment by minad** [comment]
We could also try to make the affix dispatcher more flexible. Some ideas:

~~~ elisp
((?=              . orderless-literal)      ;; (currently supported) prefix/suffix single char
 ("\\`!"          . orderless-not)          ;; only prefix regexp
 ("\\`ann:"       . orderless-annotation)   ;; verbose prefix
 ("\\`~~\\|~~\\'" . orderless-flex)         ;; two letter prefix/suffix regexp
 ("\\`$ann:"      . orderless-annotation)   ;; $ann: field matcher (annotation)
 ("\\`$mode:"     . +orderless-buffer-mode) ;; $mode: field matcher (buffer mode)
 ("\\`$.*"        . ignore))                ;; ignore $... invalid field names
~~~

Not sure if you like the regexp syntax. Another alternative notation:

~~~ elisp
((?= . orderless-literal) ;; backward compatibility
 (?= orderless-literal ?=)
 (?! orderless-not)
 ("ann:" orderless-annotation)
 ("~~" orderless-flex "~~")
 ("$ann:" orderless-annotation)
 ("$mode:" +orderless-buffer-mode)
 (?$ ignore))
~~~

Would you like a PR which adds this? I like option two for its intuitive syntax.

**Comment by karthink** [comment]
`orderless-annotation` is fantastic! No constructive comments here, just wanted to add my appreciation for your work here, @minad and @oantolin.  It's going to be very handy for in-buffer completion from rich capfs, including a capf for Org that I'm writing right now. 

I hadn't checked in on Orderless in a while -- I still had a bunch of custom style dispatchers that I wrote in 2021-22 -- so I was surprised to find them included in Orderless now.  Even the bindings are `orderless-affix-dispatch-alist` are exactly what I've been using!

> We could also document additional predicate-based matchers in the wiki or maybe implement an extensible query-language like this: `@regexp` (annotation), `@content:regexp` (buffer content) `@mode:regexp` (buffer mode), ... I think such a feature is out of scope of Orderless (as I had also mentioned in #30), also since they are completion category-dependent. But having the ability to fit such functionality into Orderless is still great.

My understanding from reading this thread is that this feature is not planned for Orderless, is this correct?

**Comment by minad** [comment]
@karthink Thanks!

> My understanding from reading this thread is that this feature is not planned for Orderless, is this correct?

Yes, I think we shouldn't add special matchers to Orderless, but it would be nice to have the base functionality available. For example in my config I have `+orderless-mode` which can match buffers in `consult-buffer` according to their mode, when I type `*mode`.

~~~ elisp
(defun +orderless-mode (pred regexp)
  "Style modifier which matches the `major-mode' of buffer against PRED and REGEXP."
  (lambda (str)
    (when-let ((buf (get-buffer (or (cdr (get-text-property 0 'multi-category str)) str)))
               (mode (buffer-local-value 'major-mode buf)))
      (orderless--match-p pred regexp (symbol-name mode)))))
~~~

In addition it may be interesting to make `orderless-affix-dispatch` more flexible. See my earlier comment https://github.com/oantolin/orderless/pull/162#issuecomment-1969667266.

**Comment by oantolin** [comment]
Well, I do like your "intuitive" notation, and think it would be useful, I just think *I* wouldn't call it intuitive. 😄 It looks like sequence notation in `rx`, but is actually more like an alternation (either this prefix *or* that suffix).

**Comment by minad** [comment]
Omar Antolín Camarena ***@***.***> writes:

> Well, I do like your "intuitive" notation, and think it would be useful, I just
> think *I* wouldn't call it intuitive. 😄 It looks like sequence notation in
> `rx`, but is actually more like an alternation (either this prefix *or* that
> suffix).

I don't have a much better proposal. One could also just add both ("~"
orderless-flex) and (orderless-flex "~") to the list but I don't like
the duplication.

**Comment by minad** [comment]
Maybe it is more elegant to leave `orderless-affix-dispatch` as is and instead use a separate "keyword" dispatcher. This dispatcher uses the syntax `:mode:org :ann:foo :on :off`. In any case, this demonstrates the extensibility of the dispatching facility.

~~~ elisp
(defvar +orderless-keywords
  '((mode . +orderless-mode)
    (on   . +orderless-on)
    (off  . +orderless-off)
    (ann  . orderless-annotation)))

(defun +orderless-off (_)
  (lambda (str)
    (when-let (sym (intern-soft str))
      (and (boundp sym) (memq sym minor-mode-list) (symbol-value sym)))))

(defun +orderless-on (_)
  (lambda (str)
    (when-let (sym (intern-soft str))
      (and (boundp sym) (memq sym minor-mode-list) (not (symbol-value sym))))))

(defun +orderless-mode (pred regexp)
  (lambda (str)
    (when-let ((buf (get-buffer (or (cdr (get-text-property 0 'multi-category str)) str)))
               (mode (buffer-local-value 'major-mode buf)))
      (orderless--match-p pred regexp (symbol-name mode)))))

(defun +orderless-keyword-dispatch (component _index _total)
  (when (string-match "\\`:\\([^:]*\\):?\\(.*\\)" component)
    (if-let ((sym (intern-soft (match-string 1 component)))
             (style (alist-get sym +orderless-keywords)))
        (cons style (match-string 2 component))
      #'ignore)))

(add-to-list 'orderless-style-dispatchers #'+orderless-keyword-dispatch)

;; BUG? Affix dispatcher errors on empty strings
(advice-add #'orderless-affix-dispatch
            :around (lambda (fun component index total)
                      (when (length> component 1)
                        (funcall fun component index total))))
~~~

**Comment by oantolin** [comment]
Hahaha: I'm so bad at remembering that `@` does annotation matching now! This time I couldn't understand why I was failing to add a work to my personal dictionary in jinx. I'm probably going to change `@` to `&` (mnemonic: "andnotation"), so I can keep my muscle memory for adding words to my personal dictionaries without glancing down to the mini-buffer.

**Comment by oantolin** [comment]
I meant changing `@` in my personal configuration, but do you think for the sake of jinx users, it might be a good idea to change the default in orderless too?

**Comment by oantolin** [comment]
I had completely forgotten there is an `rassq` function:

```elisp
(setf (car (rassq 'orderless-annotation orderless-affix-dispatch-alist)) ?&)
```

**Comment by ashton314** [comment]
> I was failing to add a word to my personal dictionary in jinx.

Yeah… this is my biggest stumbling block. @minad would you consider changing the default prefix for adding a word in Jinx? Rough guess by number of stars, scope, and age, I'd bet there are more orderless users than Jinx users.

**Comment by oantolin** [comment]
I wouldn't go by age of the project, but of the specific feature, @ashton314, and Jinx has been using `@` for much longer than orderless has! Also, for me, this is the second strike against `@` as an annotation matcher: I also had problems completing Matrix user names which start with `@`, so I'm definitely changing it in my personal configuration. I'll probably change the default here too, but I wanted to get @minad's feedback first.

**Comment by minad** [comment]
@oantolin @ashton314

I would prefer if we keep the `@` in Orderless, it is so good as a fit for annotation. However I also see the problem with this, so we should certainly document better on how to change this or how to define custom styles without the issue. I am open to changing the Jinx default save key. I agree with Ashton, that Jinx is much less popular than Orderless and the @ key is also less important there.

Global change:

~~~ elisp
(setcar (rassq 'orderless-annotation orderless-affix-dispatch-alist) ?&)
~~~

Custom style:

~~~ elisp
(orderless-define-completion-style orderless-without-at
  (orderless-affix-dispatch-alist `((?@ . nil) ,@orderless-affix-dispatch-alist)))
~~~

`consult-line` gets also hurt more and more if we eat up more special characters in Orderless.  
With my keyword dispatcher from https://github.com/oantolin/orderless/pull/162#issuecomment-1971806583, I've also observed this problem. I find the keyword dispatcher pretty nice. I've also extended it with additional keywords in the meantime. But it prevents me from easily searching for keyword symbols in `consult-line`! 

Another option would be to disable @ if completion does not provide an annotation function. Unfortunately we lack a mechanism for such dynamic (or conditional) dispatching and I am unsure if it is worth the addition.

**Comment by oantolin** [comment]
In the ended (prodded a bit by @minad 😄), I did change the default syntax for the annotation matcher to `&`.

**Pull request merged**
