### PR TITLE
Add support for completion-lazy-hilit

### PR DESCRIPTION
**Pull request by minad**
New protocol in upcoming Emacs 30, which we can even support on older Emacs versions.

See https://github.com/minad/vertico/commit/b11040e1e9c1a4e5178800a0d0925aeeb72dd027

### CODE REVIEW

**Comment by oantolin** [comment]
Do you have a link to documentation how the new protocol is supposed to be used? From the code I understand it is something like this: if `completion-lazy-hilit` is `nil` everything is as before, if it is non-nil then the following should happen:

1. Completion styles, instead of highlighting matches right away, should mutate the global variable `completion-lazy-hilit-fn` setting it to a function that can highlight candidates, the function will receive as parameter only a list of a subset of the candidates, in particular, it recieves no information on what input pattern you are matching so the function should squirrel away that information somewhere.
2. Completion UIs should apply `completion-lazy-hilit-fn` to the list of candidates they want to display before displaying them.

Is it something like that?

**Comment by minad** [comment]
> Do you have a link to documentation how the new protocol is supposed to be used?

It is part of minibuffer.el in the Emacs 30 master branch.

1. Yes.
2. Yes, the function is applied for a single candidate string and should or can mutate the candidate string.

I am running this patch with Vertico and Corfu.

**Comment by oantolin** [comment]
Oh, sorry! I see in your Vertico commit and this PR that it indeed is called with only one string at a time; not sure why I thought list. And that all that actually matters is the return value, but you're saying it is allowed to mutate the string and return it, if I understand correctly (and I see that in Vertico you call it on a copy of the candidate).

**Comment by minad** [comment]
Yes, the function is allowed to mutate, but the return value matters. Therefore I have to use a copy in Vertico. This is bad design (not my design), but this is the API in Emacs.

I'd appreciate if you merge this rather soon since Vertico/Corfu rely on this for efficiency, such that users are not affected by the change. Before that I had explicit support for Orderless lazy highlighting, see https://github.com/minad/vertico/blob/db83b0eb002550600cee00eccfc7f91991862227/vertico.el#L297.

**Comment by oantolin** [comment]
Looks good, and tests OK too. I put in `message` to make sure I was running the `completion-lazy-hilit` path after updating Vertico and all seems fine.

I also found a thread on the emacs-devel mailing list were you proposed a cleaner alternative, shame that didn't go through.

**Comment by minad** [comment]
Thanks for merging. The current solution is worse than the initial proposal, but should be mostly equivalent conceptually.

**Pull request merged**
