### PR TITLE
Fix orderless-try-completion for hash tables and alists

### PR DESCRIPTION
**Pull request by minad**
Sorry, I forgot one thing about the predicates. The predicate is called differently depending on the completion table. I hope I didn't miss anything. Please take a look!

### CODE REVIEW

**Comment by oantolin** [comment]
Heh, stateful imperative thinking leading to simpler code.

**Comment by minad** [comment]
Not to forget, it is more efficient which matters for the two times this particular code is executed :laughing:

**Comment by oantolin** [comment]
I made the mistake earlier when merging of not reading the docstring for `all-completions`, but I've read it now and I do believe this covers all the cases.

**Comment by oantolin** [comment]
It is a little weird that the docstring mentions the obarray, alist and hash table cases, but not a list of strings:

> The argument given to PREDICATE is the alist element
> or the symbol from the obarray.  If COLLECTION is a hash-table,
> predicate is called with two arguments: the key and the value.

Let's hope that's the only omission.

**Comment by minad** [comment]
Not your fault, I had thought about this before, but when submitting the PR I totally forgot about it. But I must say I dislike the design of this API. It would be much better if for cons cells, also two arguments should be used like for the hash table. If the key argument should be normalized to a string is debatable (probably not for efficiency).

**Comment by minad** [comment]
> Let's hope that's the only omission.

Yes, I mean this is the standard scenario.

**Comment by oantolin** [comment]
> It would be much better if for cons cells, also two arguments should be used like for the hash table.

Yes, that would be better.

**Pull request merged**
