### PR TITLE
Fix typos and move image to separate branch

### PR DESCRIPTION
**Pull request by minad**
Take the image from a separate branch such that it is not distributed with the ELPA/MELPA packages. I use the same trick in my packages to keep the main branch clean. This way I also avoid fiddling with the elpaignore and MELPA ignore mechanisms.

### CODE REVIEW

**Comment by oantolin** [comment]
Thank you! I didn't know how to keep the images out of the main branch.

**Comment by oantolin** [comment]
Wait, I'm confused about how git works here: if I merge this, will that create the `images` branch or do I have to do that separately. I've never seen a commit that affects two branches at once.

**Comment by minad** [comment]
Actually I abuse the image from the dispatcher branch, which is kind of ugly. You should probably create a separate images branch which just contains a single file, the image on the toplevel. Then also change the link in the README.

**Comment by oantolin** [comment]
Ah, OK, I was superconfused about why this worked.

**Comment by minad** [comment]
I think most of my packages have a dedicated screenshots branch for this purpose: https://github.com/minad/consult/tree/screenshots

**Comment by oantolin** [comment]
I just realized I could also upload the images to the wiki and link to them there.

**Pull request merged**
